# 使用 docker-compose 2.2 版本

version: "2.2"
# 定义 services
services:
  redis:
    image: redis:latest
    volumes:
      - "~/docker-demo/pv/data/:/data/"

  web:
    # 放大4倍，也就会有四个 node server
    scale: 4
    build: .
    # 新增环境变量
    environment:
      - REDIS_HOST=redis://redis:6379/0
    # 依赖关系
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    depends_on:
      - web
      - redis
    ports:
      - 80:80
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"